### ISSUE TITLE
Delimited Multiple Response uploader

### ISSUE THREAD

**Issue by GShotwell** [Crunch-io/rcrunch#149]
One common data structure for multiple response data is a delimited column where each respondent's selection is stored as a list of selections. This is a natural data source for a Crunch MR variable, but currently the way the user gets there is:
1. Splitting up the string by the delimiter
1. Combining the split up data columns with one selection per column
1. Uploading those variable to Crunch
1. Use `makeMR` to create a MR variable from the uploaded categorical variables

Since this is a pretty common pattern, it would be great if we had a function that did it all.  For the time being we thought we would just bring the data into R for processing and then upload it back to Crunch with the idea of eventually moving the logic back to the server and deriving a MR variable from a delimited text variable without moving data back and forth.

**Comment by nealrichardson** [comment]
Some considerations:

* In the SO dataset, because of the way the bare CSV importer tries to guess types, some of the variables that were semicolon-delimited MRs were made categorical and some were text. The function should work either way.
* I know a few people were able to do this as a derived variable, so you could explore doing that. Once you figure out all of the unique responses, you could conceivably compose a derivation. The big advantage of the derivation is that appending new data would work (though new responses that appear in the new data wouldn't be expressed in the derivation--that would require packaging all of the derivation composing logic into a function on the server, which would be nice but out of scope of this issue). 
* If we're creating a non-derived variable, I'd expect the user to want to replace the original column of data, which is pretty useless. We should generally think about how we'd want that to work. In my SO data cleaning code from the meetup, I see 

```
replaceVariable <- function (ds, new) {
    deleteVariable(ds, new$alias)
    return(addVariables(ds, new))
}
```

If we were replacing with a derivation, we'd want to "hide" rather than delete. Perhaps also out of scope for this issue, but related.
