### ISSUE TITLE
installing rcrunch library using devtools failed with vignettes TRUE

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/rcrunch#275]
The code snippet in the vignettes:
devtools::install_github("Crunch-io/rcrunch", build_vignettes=TRUE)

throws this error for a new user
Quitting from lines 18-21 (crunch.Rmd) 
Error: processing vignette 'crunch.Rmd' failed with diagnostics:
Must supply the email address associated with your crunch.io account
Execution halted
Installation failed: Command failed (1)

When he changes it to build_vignettes=FALSE it works. 

Thank you.

**Comment by nealrichardson** [comment]
I suspect it is because the dev version of the package depends on the dev version of [`httptest`](https://github.com/nealrichardson/httptest), and you don't have that. 

Probably nobody looks at the vignettes in the local copy of their R package since they're nicely available online in many places, including https://crunch.io/r/crunch/articles/. I'll edit the readme not to suggest `build_vignettes=TRUE`.
