### ISSUE TITLE
makeWeight not respecting exclusion

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#302]
(This is kind of urgent)

I am using makeWeight to weight a dataset. I first exclude disposition "Incomplete". Then I weight and change the exclusion and people who are disposition "Incomplete" have a value for weight. I even set weight to not be derived before changing the exclusion hoping that would fix the problem but it did not.

```[crunch] > # Exclude any respondents in the stream who have not completed the survey
[crunch] > exclusion(ds) <- ds$disposition %in% "Incomplete"
Warning message:
Variable disposition is hidden 
[crunch] > ds$disposition
Interview Disposition (categorical)
How should this case be disposed?

           Count
Complete     681
Incomplete     0
Warning message:
Variable disposition is hidden 
[crunch] > weight(ds) <- makeWeight(ds$profile_govregnew_w8 ~ c(23.31, 16, 31.56, 13.13, 4.81, 8.42, 2.77),
+         ds$age_gender_edu_granular_w8 ~ c(10.35, 2.97, 4.68, 3.91, 2.79, 2.99, 2.55, 4.94, 4.71,
+             3.07, 2.01, 3.55, 12.47, 2.79, 5.27, 4.01, 2.89, 3.44, 2.33, 5.38, 4.65, 2.55, 2.33, 3.37),
+             ds$profile_socialgrade_cie_w8 ~ c(28, 29, 21, 22),
+             name = "weight")
[crunch] > ds$disposition
Interview Disposition (categorical)
How should this case be disposed?

           Count
Complete     681
Incomplete     0
Warning message:
Variable disposition is hidden 
[crunch] > is.derived(ds$weight) <- FALSE
[crunch] > # While you can potentially have multiple weights in a dataset (assigned by weight(ds)), settings(ds)$weight
[crunch] > # is the standard (unique) weight that is seen when a user pulls up the dataset for the first time
[crunch] > settings(ds)$weight <- ds$weight
[crunch] > # Non-editors (most but not all clients) of a dataset are unable to change/remove weightings
[crunch] > settings(ds)$viewers_can_change_weight <- FALSE
[crunch] > exclusion(ds) <- NULL
[crunch] > ds$disposition
Interview Disposition (categorical)
How should this case be disposed?

               Count
Complete   681.00000
Incomplete  93.40467
```

**Comment by jonkeane** [comment]
I know that this was mostly solved via other mechanisms, but I'm curious what the motivation was for this: from above, it sounds like you wanted to set the weight of anyone who had `disposition == "Incomplete"` to NA (or, in effect: 0). Doing that would make it so that they weren't included in any of the weighted cross-tabulations in CrunchCube, which would be very similar to having them remain in the exclusion filter.

Is there some reason you can't keep disposition == "Incomplete" in the exclusion? Or is the concern something else?

**Comment by persephonet** [comment]
The reason I change the filter is so anyone who is missing a weighting variable is excluded from the data. I guess I could make the new exclusion also have disposition == “Incomplete”, but the problem is, in some datasets the exclusion isn’t based on disposition but rather a “keep” variable that I make. Some trackers include the keep variable in some waves but not others so it cannot (easily) be part of the exclusion.

Additionally, it means that people who are disposition == “Incomplete” are being used in the weighting. Meaning if all the people who are disposition == “Incomplete” are from say Northern Ireland (NI) where we normally get about 5 respondents in a survey, it will down-weight all NI people. I know this because I have made is.derived(ds$weight) <- FALSE before changing the exclusion and disposition == “Incomplete” still have a weight.

Let me know if any of that doesn’t make sense or if I can answer any more questions.

Thanks,
Persephone


Persephone Tsebelis
Senior R Programmer

[YouGov  What the world thinks]
650 5th Street, suite 505
San Francisco, CA 94107
Persephone.Tsebelis@yougov.com<mailto:Persephone.Tsebelis@yougov.com>



---------------------------------------------------

**Comment by jonkeane** [comment]
Thanks for this code and explanation. I see exactly what's going on now. 

When we fit raking weight models the algorithm _does_ ignore excluded rows correctly. The problem happens when you remove the exclusion (or when you integrate the derived weight). Instead of re-calculating the weight because the number of rows has changed, the derivation remains the same (you can see this happening in the code below). Crunch should know that it needs to re-fit the rake and do so automatically in this case. I have made a ticket for our backend team to address this, and will update this when we address that.

In the mean time, we recommend that you refit your weight model if you change the exclusion for any reason.  You can do so by running the following again (from your example):
```
weight(ds) <- makeWeight(ds$profile_govregnew_w8 ~ c(23.31, 16, 31.56, 13.13, 4.81, 8.42, 2.77),
+         ds$age_gender_edu_granular_w8 ~ c(10.35, 2.97, 4.68, 3.91, 2.79, 2.99, 2.55, 4.94, 4.71,
+             3.07, 2.01, 3.55, 12.47, 2.79, 5.27, 4.01, 2.89, 3.44, 2.33, 5.38, 4.65, 2.55, 2.33, 3.37),
+             ds$profile_socialgrade_cie_w8 ~ c(28, 29, 21, 22),
+             name = "weight")
```

You also point out that if you integrate (change from derived to non-derived) the weight variable you have the same problem: the excluded rows are given the weight they would have if they weren't excluded, but that weight over-weights responses that were excluded (again, see below). This is a slightly different problem (when integrating a raked weight excluded rows should be `No Data`), which I have also raised with the backend team. 

To reiterate: for now, we recommend that you refit your weight model if you change the exclusion for any reason.

## R code showing what's going on
Make a dataframe with 1/4 of each a, b, c, and d as well as 1, 2, 3, and 4:
```
[crunch] > letters <- factor(letters[1:4])
[crunch] > numbers <- factor(as.character(1:4))
[crunch] > 
[crunch] > df <- data.frame(letters = sample(letters, 1000, replace = TRUE),
+                  numbers = sample(numbers, 1000, replace = TRUE),
+                  id = as.character(1:1000))
[crunch] > 
```

Make a variable that will exclude most of the 'b' rows (but not all!)
```
[crunch] > df$exclude <- "no"
[crunch] > 
[crunch] > # make a variable to use as an exclusion, on purpose excludion about 75% of b rows
[crunch] > df[sample(which(df$letters == "b"), sum(df$letters == "b")*0.75), "exclude"] <- "yes"
[crunch] > 
[crunch] > ds <- newDataset(df, name = "weighting with exclusion test")
Processing the data
Uploading metadata
Uploading data
  |============================================================================================================================================| 100%
Done!
[crunch] > 
```

See that the unweighted distribution is 1/4 for each letter
```
[crunch] > ds$letters
letters (categorical)

  Count
d   263
c   251
a   244
b   242
[crunch] > 
```

Exclude the bs and see that we now have fewer bs
```
[crunch] > # exclude only some bs
[crunch] > exclusion(ds) <- ds$exclude == "yes"
[crunch] > 
[crunch] > # see the distribution of letters has few bs
[crunch] > ds$letters
letters (categorical)

  Count
d   263
c   251
a   244
b    61
[crunch] > 
```

When we weight letters each 1/4, we see that the weighted distribution is 1/4 for each letter again
```
[crunch] > # see the distribution of letters has more bs with weighting (all letters are equal)
[crunch] > ds$weight <- makeWeight(ds$letters ~ c(0.25, 0.25, 0.25, 0.25), name = "flat weight")
[crunch] > weight(ds) <- ds$weight
[crunch] > ds$letters
letters (categorical)

   Count
d 204.75
c 204.75
b 204.75
a 204.75
[crunch] > 
```

But if we remove the exclusion we see more bs suddenly.
```
[crunch] > # remove the exclusion see the distribution of letters has more bs (the weighting hasn't been refit)
[crunch] > exclusion(ds) <- NULL
[crunch] > ds$letters
letters (categorical)

     Count
b 812.2869
d 204.7500
c 204.7500
a 204.7500
```

But if we delete the weight and then re-weight, we get the proper distribution again:
```
[crunch] > delete(ds$weight)
[crunch] > ds$weight <- makeWeight(ds$letters ~ c(0.25, 0.25, 0.25, 0.25), name = "flat weight")
[crunch] > weight(ds) <- ds$weight
[crunch] > ds$letters
letters (categorical)

  Count
d   250
c   250
a   250
b   250
```
