### ISSUE TITLE
extendDataset status message needs a newline at the end

### ISSUE THREAD

**Issue by deliabailey** [Crunch-io/rcrunch#31]
see:
```
[crunch] > ds1 <- newDataset(data.frame(id=1:10), name='test1')
Processing the data
Uploading metadata
Uploading data
  |======================================================================| 100%Done!
[crunch] > ds2 <- newDataset(data.frame(id=1:10, var=letters[1:10]), name='test2')
Processing the data
Uploading metadata
Uploading data
  |======================================================================| 100%Done!
[crunch] > ds1 <- extendDataset(ds1, ds2, by='id')
  |======================================================================| 100%[crunch] >

**Comment by nealrichardson** [comment]
`?utils::setTxtProgressBar` says that the progress bar object has a `close` method, so maybe all that's missing is `close(pb)` around https://github.com/Crunch-io/rcrunch/blob/master/R/progress.R#L26; otherwise, a \n should be added.

Can (should) test this change by asserting that there should be a \n here: https://github.com/Crunch-io/rcrunch/blob/master/tests/testthat/test-progress.R#L42

https://github.com/Crunch-io/rcrunch/blob/master/tests/testthat/helper-contexts.R#L31-L37 may also need to be modified so that it doesn't fail (most tests have their progress suppressed).

**Comment by nealrichardson** [comment]
Fixed by https://github.com/Crunch-io/rcrunch/pull/34
