### ISSUE TITLE
Should we do something to avoid colliding with `dplyr::combine`?

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#359]
We got a report through support that is almost certainly a case of dplyr's combine masking crunch's and the error that is returned is inscrutable (`Error in combine_all(args) : is of unsupported type S4`). 

Although it doesn't seem to be on their pkgdown site, the function is https://github.com/tidyverse/dplyr/blob/d2e77ee6a83cd301cb7c1e73383347d69e757a9d/R/bind.r#L133-L168 and has been there + exported for at least 3 years. 

If we made ours a method for `CrunchVariables` that might be enough to coexist peacefully without any masking or having to recommend that people only load crunch after dplyr, etc.

**Comment by nealrichardson** [comment]
I don't think we can just make a method because `dplyr::combine` isn't a generic.

Some simpler things we can do:

* Make a note of this possibility in the man page for `crunch::combine`
* Provide aliases `combineCategories` and `combineResponses` and recommend either using those or `crunch::combine()` if you've encountered this masking.
