### ISSUE TITLE
Add function for grouping together of categories that allows for overlap

### ISSUE THREAD

**Issue by gergness** [Crunch-io/rcrunch#396]
Users want to be able to MR variables that have overlapping group of categories. The most common reason a user wants this currently is when there's a time series, so that they can calculate moving averages. (Long term we will solve this when we have wave variables that include concept of time).

## Mike's "hack" code that works, that we want to encapsulate

```
timevar <- 'Month'
monthcats <- categories(ds[[timevar]])
​
monthcats <- monthcats[-length(monthcats),]
​
stride <- 6
step <- 3
offset <- 0
​
stride <- stride-1 # consder current in stride calc (count yourself)
out_sequence <- seq.int(from=1, to=(length(monthcats)- stride - offset), by=step)
​
exprs <- map(out_sequence, function(pd) {
    ds[[timevar]] %in% (ids(rev(monthcats)[ pd : (pd+stride) ]))
})
newnames <- map(out_sequence, function(pd) {
    paste(names(rev(monthcats))[pd+stride], names(rev(monthcats))[pd], sep='–')
})
​
newvars <- map2(exprs, newnames, function(expr,newname){
    return (VariableDefinition(name=newname, derivation=crunch:::zcl(expr)$args[[1]], alias=newname))
})
​
ds <- addVariables(ds, newvars)
ds[[paste0('derived',stride+1,'m2')]] <- makeMR(ds[rev(unlist(newnames))], selections = "Selected", name=paste(stride+1,"Month v2"))
```

## API Inspiration
Similar problem to the one solved by https://davisvaughan.github.io/slider/reference/slide.html

**Comment by gergness** [comment]
@Malecki - noodling on a function call (I'm using the `slider` nomenclature, which I think conflicts with yours for `stride` - their `stride` is more similar to your `step`, and your `step` is replaced by the `before`/`after`.

They don't have an `offset` so I included it, though I'm not sure it's as useful when there is a `complete` argument.

```
makeSlidingMR <- function(
  variable, # a categorical crunch variable
  before = 0, # number of categories before stride to include
  after = 0, # number of categories after stride to include
  stride = 1, # how many categories to jump between before looking before/after
  offset = 0, # offset from end to stop when striding
  include.missing = FALSE, # whether to include categories marked as missing
  complete = FALSE # Whether 
) {
  ...
}
```

**Comment by mattsteele-crunch** [comment]
Hello, 

Our customer (potentially others) is looking for R code that can automatically generate MR variables.

Mike didn't want to share this code in it's current format... can you please let me know when the code will be ready in a format that is shareable? 

Note: I've been able to apply the code to other data, and it works fine. I just tidied it up so that the "changeable" bits are all at the top (offset, stride, etc)... could this be put into a function within library(crunch)? 

Customer needs this as soon as possible (ie: by Wed 19th Feb 2020)

Links to issue described at: https://help.crunch.io/hc/en-us/articles/360039873451
