### ISSUE TITLE
Grab existing derivations 

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#98]
Derived variables can be represented as crunch variables, users should be able to use `derivation` to see what the expression is that generates the derived variable.

**Comment by nealrichardson** [comment]
And also update (`PATCH`) a derivation with `derivation<-`

Getting and printing the derivation by reaching into unexported methods now:

```
[crunch] > k <- crunch:::CrunchExpr(expression=entity(ds$age)@body$derivation)
[crunch] > k@expression$args[[2]]$variable <- crunch:::absoluteURL(k@expression$args[[2]]$variable, self(ds$age))
[crunch] > k
Crunch expression: 2013L - birthyr
```

For the relative URLs, write something that recurses through the expression and calls absoluteURL on any list named “variable”

Also should pass `control=NULL` into deparse here: https://github.com/Crunch-io/rcrunch/blob/master/R/show.R#L181 so that that `2013L` prints as `2013`
